#!/usr/bin/env python3
"""
Plot per-joint tracking figures from deploy_log_*.csv.

Usage:
    python3 tools/plot_deploy_tracking.py data/deploy_log_xxx.csv
    python3 tools/plot_deploy_tracking.py data/deploy_log_xxx.csv --outdir plots/custom_run
"""

import argparse
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


JOINT_NAMES = [
    "l_yaw",
    "l_roll",
    "l_pitch",
    "l_knee",
    "l_ankle",
    "r_yaw",
    "r_roll",
    "r_pitch",
    "r_knee",
    "r_ankle",
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot per-joint tracking figures from deploy_log CSV."
    )
    parser.add_argument(
        "csv_path",
        help="Path to deploy_log_*.csv generated by the deployment program.",
    )
    parser.add_argument(
        "--outdir",
        default=None,
        help="Output directory for PNG figures. Default: plots/<csv_stem>/",
    )
    return parser.parse_args()


def ensure_required_columns(df: pd.DataFrame):
    required = {"timestamp_local", "record_type", "event_type"}
    for i in range(10):
        required.update(
            {
                f"q_exp_{i}",
                f"dq_exp_{i}",
                f"tau_exp_{i}",
                f"q_{i}",
                f"dq_{i}",
                f"tau_{i}",
            }
        )

    missing = [column for column in sorted(required) if column not in df.columns]
    if missing:
        raise ValueError(f"CSV 缺少必要列: {', '.join(missing)}")


def load_dataframe(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"找不到 CSV 文件: {csv_path}")

    df = pd.read_csv(csv_path)
    ensure_required_columns(df)

    df["timestamp_dt"] = pd.to_datetime(df["timestamp_local"], errors="coerce")
    if df["timestamp_dt"].isna().all():
        raise ValueError("timestamp_local 无法解析为时间戳")

    valid_timestamps = df["timestamp_dt"].dropna()
    t0 = valid_timestamps.iloc[0]
    df["t_sec"] = (df["timestamp_dt"] - t0).dt.total_seconds()
    return df


def build_default_outdir(csv_path: Path) -> Path:
    return Path("plots") / csv_path.stem


def add_event_lines(ax, event_df: pd.DataFrame, y_text_anchor: float):
    if event_df.empty:
        return

    for _, event in event_df.iterrows():
        t_event = event["t_sec"]
        if pd.isna(t_event):
            continue
        ax.axvline(t_event, color="tab:red", linestyle="--", linewidth=1.0, alpha=0.65)

    labeled_events = event_df.dropna(subset=["t_sec"]).head(8)
    for _, event in labeled_events.iterrows():
        event_type = str(event.get("event_type", "")).strip() or "event"
        ax.text(
            event["t_sec"],
            y_text_anchor,
            event_type,
            rotation=90,
            va="top",
            ha="right",
            fontsize=8,
            color="tab:red",
            alpha=0.85,
        )


def plot_joint(tracking_df: pd.DataFrame, event_df: pd.DataFrame, joint_idx: int, output_path: Path):
    joint_name = JOINT_NAMES[joint_idx]
    t_sec = tracking_df["t_sec"]

    fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
    fig.suptitle(f"Joint {joint_idx} ({joint_name}) Tracking", fontsize=14)

    specs = [
        ("Position", f"q_exp_{joint_idx}", f"q_{joint_idx}", "rad"),
        ("Velocity", f"dq_exp_{joint_idx}", f"dq_{joint_idx}", "rad/s"),
        ("Torque", f"tau_exp_{joint_idx}", f"tau_{joint_idx}", "Nm"),
    ]

    for ax, (title, expected_col, actual_col, ylabel) in zip(axes, specs):
        expected = tracking_df[expected_col]
        actual = tracking_df[actual_col]

        ax.plot(t_sec, expected, label="expected", linewidth=1.4, color="tab:blue")
        ax.plot(t_sec, actual, label="actual", linewidth=1.2, color="tab:orange", alpha=0.9)
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linestyle="--", linewidth=0.5, alpha=0.45)
        ax.legend(loc="upper right")

        y_min = min(expected.min(), actual.min())
        y_max = max(expected.max(), actual.max())
        y_anchor = y_max - 0.02 * (y_max - y_min) if y_max > y_min else y_max
        add_event_lines(ax, event_df, y_anchor)

    axes[-1].set_xlabel("Time since start (s)")
    fig.tight_layout(rect=[0.0, 0.03, 1.0, 0.97])
    fig.savefig(output_path, dpi=180)
    plt.close(fig)


def plot_imu_triplet(
    tracking_df: pd.DataFrame,
    event_df: pd.DataFrame,
    columns,
    titles,
    ylabel: str,
    output_path: Path,
    fig_title: str,
):
    t_sec = tracking_df["t_sec"]

    fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)
    fig.suptitle(fig_title, fontsize=14)

    for ax, column, title in zip(axes, columns, titles):
        values = tracking_df[column]
        ax.plot(t_sec, values, linewidth=1.4, color="tab:green")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linestyle="--", linewidth=0.5, alpha=0.45)

        y_min = values.min()
        y_max = values.max()
        y_anchor = y_max - 0.02 * (y_max - y_min) if y_max > y_min else y_max
        add_event_lines(ax, event_df, y_anchor)

    axes[-1].set_xlabel("Time since start (s)")
    fig.tight_layout(rect=[0.0, 0.03, 1.0, 0.97])
    fig.savefig(output_path, dpi=180)
    plt.close(fig)


def main():
    args = parse_args()
    csv_path = Path(args.csv_path).expanduser().resolve()
    outdir = Path(args.outdir).expanduser().resolve() if args.outdir else build_default_outdir(csv_path).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    df = load_dataframe(csv_path)
    tracking_df = df[df["record_type"] == "inference"].copy()
    event_df = df[df["record_type"] == "event"].copy()

    if tracking_df.empty:
        raise ValueError("CSV 中没有 inference 行，无法绘制跟踪曲线")

    for joint_idx, joint_name in enumerate(JOINT_NAMES):
        output_path = outdir / f"joint_{joint_idx}_{joint_name}.png"
        plot_joint(tracking_df, event_df, joint_idx, output_path)
        print(f"已保存: {output_path}")

    imu_plot_specs = [
        (
            ["omega_x", "omega_y", "omega_z"],
            ["Omega X", "Omega Y", "Omega Z"],
            "rad/s",
            outdir / "imu_omega.png",
            "IMU Angular Velocity",
        ),
        (
            ["acc_x", "acc_y", "acc_z"],
            ["Acc X", "Acc Y", "Acc Z"],
            "m/s^2",
            outdir / "imu_acc.png",
            "IMU Acceleration",
        ),
        (
            ["raw_roll", "raw_pitch", "raw_yaw"],
            ["Raw Roll", "Raw Pitch", "Raw Yaw"],
            "rad",
            outdir / "imu_euler_raw.png",
            "IMU Raw Euler Angles",
        ),
        (
            ["roll", "pitch", "yaw"],
            ["Compensated Roll", "Compensated Pitch", "Compensated Yaw"],
            "rad",
            outdir / "imu_euler_compensated.png",
            "IMU Compensated Euler Angles",
        ),
    ]

    for columns, titles, ylabel, output_path, fig_title in imu_plot_specs:
        plot_imu_triplet(
            tracking_df=tracking_df,
            event_df=event_df,
            columns=columns,
            titles=titles,
            ylabel=ylabel,
            output_path=output_path,
            fig_title=fig_title,
        )
        print(f"已保存: {output_path}")

    print(f"全部完成，输出目录: {outdir}")


if __name__ == "__main__":
    main()
